# Generated by Django 5.1.3 on 2025-04-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
